export const HOT_TAKE_CATEGORIES = [
  "Messi",
  "Ronaldo",
  "Neymar",
  "Mbappé",
  "Yamal",
  "World Cup",
  "Barcelona",
  "Real Madrid",
  "Legends",
  "Managers",
  "Transfers",
  "Modern Football",
  "GOAT Debates",
  "National Teams",
  "Underrated",
  "Overrated",
  "Champions League",
  "La Masia",
] as const;

export type HotTakeCategory = (typeof HOT_TAKE_CATEGORIES)[number];
export type HotTakeEra = "classic" | "2000s" | "2010s" | "modern" | "timeless";

export interface HotTake {
  id: string;
  text: string;
  category: HotTakeCategory;
  era: HotTakeEra;
  controversialScore: number;
  agreePercentage: number;
  disagreePercentage: number;
}

type TakeSeed = readonly [string, HotTakeCategory, HotTakeEra, number, number];

const seeds: TakeSeed[] = [
  ["Prime Neymar was more entertaining than Messi.", "Neymar", "2010s", 86, 42],
  ["Messi is the greatest World Cup player ever.", "Messi", "timeless", 54, 76],
  ["Messi's 2022 final was the best individual final performance.", "Messi", "modern", 66, 71],
  ["Messi was a better playmaker than Maradona.", "Messi", "timeless", 71, 59],
  ["Messi's Barcelona peak was higher than any player's club peak.", "Messi", "2010s", 62, 74],
  ["Messi could have won more Ballons d'Or in a different era.", "Messi", "timeless", 47, 68],
  ["Messi's international legacy is now untouchable.", "Messi", "modern", 44, 81],
  ["Messi is more clutch than Ronaldo in big tournaments.", "Messi", "timeless", 80, 56],
  ["Messi should have left Barcelona earlier.", "Messi", "2010s", 58, 38],
  ["Ronaldo's 2018 World Cup performance is underrated.", "Ronaldo", "2010s", 63, 64],
  ["Ronaldo would trade club records for a World Cup medal.", "Ronaldo", "timeless", 52, 71],
  ["Ronaldo was a better knockout player than Messi.", "Ronaldo", "timeless", 79, 54],
  ["Ronaldo's Juventus move hurt his legacy.", "Ronaldo", "2010s", 68, 52],
  ["Ronaldo was never the best technical player of his era.", "Ronaldo", "2000s", 61, 66],
  ["Ronaldo's longevity is football's greatest achievement.", "Ronaldo", "modern", 43, 84],
  ["Portugal underachieved with Ronaldo's generation.", "Ronaldo", "2010s", 72, 69],
  ["Ronaldo's legacy would look different with a World Cup final.", "Ronaldo", "timeless", 64, 66],
  ["Neymar was Brazil's best player since Ronaldo Nazário.", "Neymar", "2010s", 57, 73],
  ["Neymar should have stayed at Barcelona.", "Neymar", "2010s", 76, 78],
  ["Neymar was more talented than Mbappé.", "Neymar", "modern", 82, 61],
  ["Neymar's PSG years are judged too harshly.", "Neymar", "modern", 60, 68],
  ["Neymar deserved a World Cup final more than most winners.", "Neymar", "2010s", 59, 58],
  ["Neymar is still football's most misunderstood superstar.", "Neymar", "modern", 67, 68],
  ["Neymar's injuries cost football a true all-time peak.", "Neymar", "2010s", 50, 82],
  ["Mbappé will finish above Messi in World Cup legacy.", "Mbappé", "modern", 89, 44],
  ["Mbappé is already France's greatest World Cup attacker.", "Mbappé", "modern", 55, 53],
  ["Mbappé will become the greatest French player ever.", "Mbappé", "modern", 62, 64],
  ["Mbappé's 2022 final was better than most World Cup-winning displays.", "Mbappé", "modern", 60, 72],
  ["Mbappé needs a Champions League legacy to reach the very top.", "Mbappé", "modern", 49, 74],
  ["Mbappé is more dangerous than prime Henry.", "Mbappé", "modern", 74, 46],
  ["Mbappé should have left PSG years earlier.", "Mbappé", "modern", 52, 70],
  ["Yamal has a higher ceiling than Neymar.", "Yamal", "modern", 92, 37],
  ["Lamine Yamal is already good enough to start a World Cup final.", "Yamal", "modern", 65, 64],
  ["Yamal will surpass Neymar's club legacy.", "Yamal", "modern", 88, 40],
  ["Yamal is the most exciting teenage talent since Messi.", "Yamal", "modern", 57, 71],
  ["Yamal should be protected from too much football.", "Yamal", "modern", 36, 83],
  ["Yamal has more natural flair than Mbappé.", "Yamal", "modern", 79, 48],
  ["Yamal is already Barcelona's most important attacker.", "Yamal", "modern", 70, 55],
  ["A World Cup matters more than a Champions League.", "World Cup", "timeless", 48, 79],
  ["The World Cup is football's only truly global stage.", "World Cup", "timeless", 35, 86],
  ["Expanding the World Cup makes it less special.", "World Cup", "modern", 58, 56],
  ["Penalty shootouts are the perfect way to decide a knockout match.", "World Cup", "timeless", 83, 49],
  ["A World Cup host should receive an automatic place.", "World Cup", "timeless", 54, 47],
  ["The best World Cup stories always come from underdogs.", "World Cup", "timeless", 38, 86],
  ["World Cup pressure exposes players more than club football.", "World Cup", "timeless", 44, 78],
  ["The World Cup should never be played in winter.", "World Cup", "modern", 69, 62],
  ["Barcelona would have won more Champions Leagues if Neymar stayed.", "Barcelona", "2010s", 74, 67],
  ["Barcelona's identity matters more than winning ugly.", "Barcelona", "timeless", 58, 61],
  ["Barcelona should always build around academy players.", "Barcelona", "modern", 52, 72],
  ["Barcelona's 2011 side is the best club team ever.", "Barcelona", "2010s", 46, 81],
  ["Barcelona should have sold Messi before 2021.", "Barcelona", "2010s", 81, 31],
  ["Barcelona fans romanticise possession football too much.", "Barcelona", "modern", 67, 48],
  ["Pedri will never reach Iniesta's level.", "Barcelona", "modern", 71, 62],
  ["Real Madrid's Champions League magic is a real thing.", "Real Madrid", "timeless", 43, 77],
  ["Real Madrid are the greatest club in football history.", "Real Madrid", "timeless", 52, 76],
  ["Real Madrid care more about stars than systems.", "Real Madrid", "modern", 62, 57],
  ["Real Madrid's best teams are less fun than Barcelona's best teams.", "Real Madrid", "2010s", 69, 54],
  ["Real Madrid should never rebuild while winning trophies.", "Real Madrid", "modern", 57, 64],
  ["Vinícius Jr is already a Real Madrid legend.", "Real Madrid", "modern", 50, 69],
  ["Galáctico signings make Real Madrid more entertaining.", "Real Madrid", "2000s", 45, 72],
  ["Prime Ronaldinho was more fun to watch than prime Messi.", "Legends", "2000s", 83, 51],
  ["Maradona had the single greatest World Cup tournament.", "Legends", "classic", 52, 72],
  ["Pelé's legacy needs no defence from modern fans.", "Legends", "classic", 34, 81],
  ["Zidane had more big-game aura than any modern midfielder.", "Legends", "2000s", 44, 79],
  ["Ronaldo Nazário was the most complete striker ever.", "Legends", "2000s", 53, 75],
  ["Past World Cup legends played in tougher conditions.", "Legends", "classic", 48, 66],
  ["The best era of football is the one you watched growing up.", "Legends", "timeless", 62, 74],
  ["Guardiola's Barcelona is the best club team ever.", "Managers", "2010s", 42, 82],
  ["A manager matters more than a captain at the World Cup.", "Managers", "timeless", 67, 45],
  ["Managers should make substitutions earlier in knockout games.", "Managers", "modern", 46, 63],
  ["Great managers build systems, not superstar lineups.", "Managers", "modern", 40, 76],
  ["Ancelotti is the best cup manager of all time.", "Managers", "modern", 57, 68],
  ["International managers deserve more credit than club managers.", "Managers", "timeless", 61, 55],
  ["Managers are too obsessed with control in modern football.", "Managers", "modern", 63, 64],
  ["Transfers should pause during a World Cup summer.", "Transfers", "modern", 49, 61],
  ["A player should always leave when a dream club calls.", "Transfers", "timeless", 59, 58],
  ["Loyalty matters more than chasing the biggest salary.", "Transfers", "timeless", 65, 71],
  ["Loan moves are better for young players than big transfers.", "Transfers", "modern", 43, 73],
  ["The Saudi league changed the transfer market for good.", "Transfers", "modern", 68, 56],
  ["Players move clubs too often to become true legends.", "Transfers", "modern", 57, 69],
  ["Free transfers are better for football than record fees.", "Transfers", "modern", 51, 63],
  ["Modern football is less entertaining than 2010s football.", "Modern Football", "modern", 74, 59],
  ["VAR has made football fairer overall.", "Modern Football", "modern", 56, 54],
  ["Data has improved football more than it has hurt creativity.", "Modern Football", "modern", 52, 62],
  ["Football is better when players show personality on the pitch.", "Modern Football", "modern", 36, 84],
  ["Modern players are better athletes than past legends.", "Modern Football", "modern", 58, 62],
  ["Tactics have made top-level football too cautious.", "Modern Football", "modern", 61, 57],
  ["Social media has made football debates worse.", "Modern Football", "modern", 47, 82],
  ["Messi is the GOAT because he completes football better than anyone.", "GOAT Debates", "timeless", 60, 72],
  ["Ronaldo is the GOAT because he mastered every challenge.", "GOAT Debates", "timeless", 77, 47],
  ["A player can be a true all-time great without a World Cup.", "GOAT Debates", "timeless", 41, 82],
  ["The GOAT debate is more fun without a final answer.", "GOAT Debates", "timeless", 46, 75],
  ["Peak ability matters more than career longevity in GOAT debates.", "GOAT Debates", "timeless", 72, 48],
  ["Winning with your national team should decide the GOAT debate.", "GOAT Debates", "timeless", 68, 51],
  ["The greatest player is not always the greatest winner.", "GOAT Debates", "timeless", 39, 85],
  ["International football is more emotional than club football.", "National Teams", "timeless", 43, 74],
  ["Brazil should always play beautiful football, even if it costs results.", "National Teams", "timeless", 58, 67],
  ["France have more World Cup depth than any country right now.", "National Teams", "modern", 51, 61],
  ["England are judged more harshly than any other national team.", "National Teams", "modern", 47, 65],
  ["National team loyalty is football's best tradition.", "National Teams", "timeless", 35, 80],
  ["A nation's style matters as much as winning the trophy.", "National Teams", "timeless", 55, 60],
  ["South American teams bring more personality to tournaments.", "National Teams", "timeless", 59, 59],
  ["Thomas Müller is one of football's most underrated greats.", "Underrated", "2010s", 43, 74],
  ["Griezmann is more important than he gets credit for.", "Underrated", "modern", 44, 77],
  ["Modrić is the most complete midfielder of his generation.", "Underrated", "2010s", 50, 71],
  ["Kanté at his peak was world-class in any era.", "Underrated", "2010s", 47, 75],
  ["David Villa deserves more all-time striker respect.", "Underrated", "2000s", 54, 67],
  ["Di María belongs in Argentina's greatest-ever XI.", "Underrated", "modern", 60, 62],
  ["Roberto Firmino was more valuable than his numbers show.", "Underrated", "2010s", 62, 58],
  ["The Ballon d'Or overrates goalscorers.", "Overrated", "timeless", 69, 63],
  ["The Premier League is overrated by its own fans.", "Overrated", "modern", 76, 49],
  ["Possession stats are overrated in knockout football.", "Overrated", "modern", 55, 68],
  ["Transfer fees are a terrible way to judge players.", "Overrated", "modern", 43, 78],
  ["Unbeaten seasons are overrated compared with trophies.", "Overrated", "timeless", 57, 60],
  ["The Golden Boot is overrated as an individual award.", "Overrated", "timeless", 54, 54],
  ["Football nostalgia is more honest than football analysis.", "Overrated", "timeless", 71, 46],
  ["The Champions League is better than domestic leagues every year.", "Champions League", "modern", 57, 64],
  ["Champions League knockout nights are football's best product.", "Champions League", "timeless", 42, 83],
  ["The away-goals rule made European ties more exciting.", "Champions League", "2010s", 68, 58],
  ["Winning one Champions League can define a player's legacy.", "Champions League", "timeless", 50, 72],
  ["The Champions League format should have stayed simple.", "Champions League", "modern", 49, 74],
  ["A great domestic season can matter more than a Champions League run.", "Champions League", "timeless", 62, 53],
  ["The Champions League rewards squad depth too much.", "Champions League", "modern", 59, 56],
  ["La Masia is football's greatest academy.", "La Masia", "timeless", 45, 82],
  ["La Masia players understand Barcelona better than any signing can.", "La Masia", "modern", 51, 70],
  ["Barcelona should risk losing more games to play academy talent.", "La Masia", "modern", 61, 57],
  ["Gavi brings more to Barcelona than most fans admit.", "La Masia", "modern", 48, 72],
  ["La Masia's 2008 generation may never be matched.", "La Masia", "2000s", 37, 84],
  ["The academy should be Barcelona's first transfer strategy.", "La Masia", "modern", 52, 73],
  ["La Masia is more important to football than any expensive squad.", "La Masia", "timeless", 58, 65],
  ["Haaland is more valuable than any playmaker in a final.", "Modern Football", "modern", 74, 45],
  ["Bellingham has the mentality to become England's greatest ever player.", "National Teams", "modern", 63, 61],
  ["Vinícius Jr is the most feared winger in football.", "Real Madrid", "modern", 55, 72],
  ["Kroos retired at exactly the right time.", "Legends", "modern", 42, 78],
  ["Iniesta was better than Xavi in the biggest matches.", "Barcelona", "2010s", 66, 52],
  ["Saka should be England's first name on the team sheet.", "National Teams", "modern", 49, 73],
  ["Goalkeepers should win more Ballons d'Or.", "Underrated", "timeless", 56, 69],
  ["Defenders deserve as much spotlight as scorers.", "Underrated", "timeless", 39, 81],
  ["The 2014 Germany side is more memorable than the 2010 Spain side.", "World Cup", "2010s", 70, 43],
  ["Argentina versus France in 2022 cannot be topped as a World Cup final.", "World Cup", "modern", 46, 75],
  ["A red card can make a match more entertaining.", "Overrated", "timeless", 81, 38],
  ["Football needs more villains, not fewer.", "Overrated", "modern", 64, 63],
  ["The best players should take every penalty in a shootout.", "Managers", "timeless", 53, 71],
  ["A captain should never be substituted in a final.", "Managers", "timeless", 71, 46],
  ["Clubs should stop buying teenagers for huge fees.", "Transfers", "modern", 59, 66],
  ["A player moving to a rival can never be a club legend again.", "Transfers", "timeless", 68, 54],
  ["The 2000s had better football boots and better vibes.", "Legends", "2000s", 57, 69],
  ["Every team needs one player who tries the impossible pass.", "Modern Football", "timeless", 37, 85],
  ["The best football debates have no correct answer.", "GOAT Debates", "timeless", 35, 88],
  ["Winning ugly is still better than losing beautifully.", "National Teams", "timeless", 62, 58],
];

export const HOT_TAKES: HotTake[] = seeds.map(
  ([text, category, era, controversialScore, agreePercentage], index) => ({
    id: `hot-take-${index + 1}`,
    text,
    category,
    era,
    controversialScore,
    agreePercentage,
    disagreePercentage: 100 - agreePercentage,
  }),
);
