create table if not exists public.higher_lower_leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null default 'Anonymous' check (char_length(player_name) between 1 and 40),
  streak integer not null check (streak >= 0),
  category text not null default 'All Categories' check (char_length(category) between 1 and 80),
  created_at timestamptz not null default now()
);

alter table public.higher_lower_leaderboard enable row level security;

create policy "Anyone can read higher lower scores"
  on public.higher_lower_leaderboard for select
  to anon
  using (true);

create policy "Anyone can submit higher lower scores"
  on public.higher_lower_leaderboard for insert
  to anon
  with check (
    streak between 0 and 9999
    and char_length(player_name) between 1 and 40
    and char_length(category) between 1 and 80
  );

create index if not exists higher_lower_leaderboard_streak_created_at_idx
  on public.higher_lower_leaderboard (streak desc, created_at asc);
